#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.fogg_peering_net_stag_prod')" != "$FOGG_PEERING_NET_STAG_PROD_VERSION" ]]; then
    return 1
  fi

  return 0
}

main "$@"
