#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_peering_net_stag_prod="0.0.1"
  jq -n --arg fogg_peering_net_stag_prod "$ver_fogg_peering_net_stag_prod" '{fogg_peering_net_stag_prod: $fogg_peering_net_stag_prod}'
}

version "$@"
